FROM node:lts-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Taken care of by docker-compose already via a volume. We may not need this with docker-compose,
# but it's here for reference and in case we choose not to use docker-compose.
COPY . .

CMD ["npm", "run", "start"]
