name: Deploy Frontend
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t cswitzer/react-test -f Dockerfile.dev .
            # lets React know that it is running in a CI environment, so no interactive mode
            - run: docker run -e CI=true cswitzer/react-test npm run test
